from django.urls import path

from . import views


urlpatterns = [
    path('', views.FilmView.as_view(), name='index'),
    path('action/', views.Action.as_view(), name='action'),
    path('action/insert_all/', views.Action.as_view(), name='insert_all'),
    path('action/merge/', views.Action.as_view(), name='merge'),
    path('action/save_tag/', views.save_tag, name='save_tag'),
    path('action/insert_tag/', views.insert_tag, name='insert_tag'),
    path('action/add_default_tag/', views.add_default_tag, name='add_default_tag'),
    path('series/', views.SeriesView.as_view(), name='series'),
    path('series/add/', views.SeriesCreateView.as_view(), name='series-add'),
    path('series/<str:series_url>/', views.SeriesDetailView.as_view(), name='series-detail'),
    path('series/<str:series_url>/edit/', views.SeriesUpdateView.as_view(), name='series-update'),
    path('series/<str:series_url>/delete/', views.SeriesDeleteView.as_view(), name='series-delete'),
    path('director/', views.DirectorView.as_view(), name='director'),
    path('director/add/', views.DirectorCreateView.as_view(), name='director-add'),
    path('director/<str:director_url>/', views.DirectorDetailView.as_view(), name='director-detail'),
    path('director/<str:director_url>/edit/', views.DirectorUpdateView.as_view(), name='director-update'),
    path('director/<str:director_url>/delete/', views.DirectorDeleteView.as_view(), name='director-delete'),
    path('studio/', views.StudioView.as_view(), name='studio'),
    path('studio/add/', views.StudioCreateView.as_view(), name='studio-add'),
    path('studio/<str:studio_url>/', views.StudioDetailView.as_view(), name='studio-detail'),
    path('studio/<str:studio_url>/edit/', views.StudioUpdateView.as_view(), name='studio-update'),
    path('studio/<str:studio_url>/delete/', views.StudioDeleteView.as_view(), name='studio-delete'),
    path('actor/', views.ActorView.as_view(), name='actor'),
    path('actor/add/', views.ActorCreateView.as_view(), name='actor-add'),
    path('actor/<str:actor_url>/', views.ActorDetailView.as_view(), name='actor-detail'),
    path('actor/<str:actor_url>/edit/', views.ActorUpdateView.as_view(), name='actor-update'),
    path('actor/<str:actor_url>/delete/', views.ActorDeleteView.as_view(), name='actor-delete'),
    path('tag/', views.TagView.as_view(), name='tag'),
    path('tag/add/', views.TagCreateView.as_view(), name='tag-add'),
    path('tag/<str:tag_url>/', views.TagDetailView.as_view(), name='tag-detail'),
    path('tag/<str:tag_url>/edit/', views.TagUpdateView.as_view(), name='tag-update'),
    path('tag/<str:tag_url>/delete/', views.TagDeleteView.as_view(), name='tag-delete'),
    path('film/add/', views.FilmCreateView.as_view(), name='film-add'),
    path('film/<str:film_url>/', views.FilmDetailView.as_view(), name='film-detail'),
    path('film/<str:film_url>/edit/', views.FilmUpdateView.as_view(), name='film-update'),
    path('film/<str:film_url>/delete/', views.FilmDeleteView.as_view(), name='film-delete'),
    path('film/<str:film_url>/play/', views.add_player, name='film-play'),
    path('film/<str:film_url>/add_one_tag/', views.add_one_tag, name='film-add_tag'),
]